# Generated by Django 3.0.4 on 2020-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhonebookApp', '0002_auto_20200408_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
    ]
