# Generated by Django 3.0.4 on 2020-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhonebookApp', '0004_auto_20200411_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, default='No Email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, default='No Phone Number', max_length=50, verbose_name='Phone number'),
        ),
    ]
